# Generated by Django 5.0 on 2024-01-10 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('season', models.CharField(max_length=200)),
                ('price', models.CharField(default='noprice', max_length=5)),
                ('image', models.ImageField(upload_to='imgs/products')),
                ('category', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('Color', models.ManyToManyField(to='products.color')),
                ('Material', models.ManyToManyField(to='products.material')),
                ('Product', models.ManyToManyField(to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
    ]
